# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170119_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 9, 22, 32, 624834, tzinfo=utc)),
        ),
    ]
